[package]
name = "move_hackathon"
version = "1.0.0"
authors = []

[addresses]
move_hackathon = "0xdd525d357675655d18cecf68c3a7f29de3cda46ba4e4d0065ac9debdb8982575"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "m1"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
